name: connectivity_example
description: Demonstrates how to use the connectivity plugin.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_connectivity:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
